-- Conversation Memory Schema
-- Version: 002
-- Description: Add conversation memory table for storing summaries and key facts

-- Conversation memory table for intelligent context management
CREATE TABLE conversation_memory (
  conversation_id TEXT PRIMARY KEY REFERENCES conversations(id) ON DELETE CASCADE,
  
  -- Summary of older messages (generated by LLM)
  summary TEXT,
  
  -- Key facts extracted from conversation (JSON array)
  -- Example: ["user prefers Python", "working on web app", "name is John"]
  key_facts TEXT DEFAULT '[]',
  
  -- Tracking when summary was last updated
  last_summarized_at TEXT,
  
  -- Message count when last summarized (to know when to re-summarize)
  message_count_at_summary INTEGER DEFAULT 0,
  
  -- Last message ID that was included in the summary
  last_summarized_message_id TEXT,
  
  -- Timestamps
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

-- Index for quick lookups
CREATE INDEX idx_conversation_memory_updated ON conversation_memory(updated_at DESC);

